# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Scheduled runs

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 20 * * *'

permissions:
  contents: read

jobs:
  EDA:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        pip install -r requirements/requirements_app.txt
    - name: Run EDA
      run: |
        export PYTHONPATH=$PWD:$PYTHONPATH
        python save_life_in_ua/eda.py