# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Generate docs

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '10 20 * * *'

permissions:
  contents: write

jobs:
  EDA:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        pip install -r requirements/requirements_app.txt
    - name: Check datetime
      run: |
        date
    - name: Run EDA
      run: |
        export PYTHONPATH=$PWD:$PYTHONPATH
        python save_life_in_ua/eda.py
    - name: Deploy pages 🚀
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: docs # The folder the action should deploy.