# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Scheduled runs

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 20 * * *'

permissions:
  contents: read

jobs:
  EDA:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
    - name: Set up Python 3
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        pip install -r requirements/requirements_app.txt
    - name: Check datetime
      run: |
        date
    - name: Run EDA
      run: |
        export PYTHONPATH=$PWD:$PYTHONPATH
        python save_life_in_ua/eda.py
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply php-cs-fixer changes
        file_pattern: docs/
        branch: gh-pages
    - name: "Run if changes have been detected"
      if: steps.auto-commit-action.outputs.changes_detected == 'true'
      run: echo "Changes!"
    - name: "Run if no changes have been detected"
      if: steps.auto-commit-action.outputs.changes_detected == 'false'
      run: echo "No Changes!"